import { Provider } from '@/components/sessionProvider'
import { Inter } from 'next/font/google'
import './globals.css'
import AppMenu from '@/components/appMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body className={`${inter.className}`}>
        <Provider> 
          {children}
        </ Provider>
      </body> 
      {/* design the menu */}
    </html>
  )
}
